"""Add Rating Publication models

Revision ID: 616ab06a2d4c
Revises: 
Create Date: 2024-02-06 13:49:54.934178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '616ab06a2d4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_user_email'), 'auth_user', ['email'], unique=True)
    op.create_table('publication',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(length=4096), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('counter_of_votes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('publication_rating', sa.Integer(), nullable=False),
    sa.CheckConstraint('counter_of_votes >= 0', name='positive_value_non_negative'),
    sa.ForeignKeyConstraint(['author_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('like_is_toggeled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('publication')
    op.drop_index(op.f('ix_auth_user_email'), table_name='auth_user')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
